# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER course

# 挂载目录
VOLUME /home/course
# 创建目录
RUN mkdir -p /home/course
# 指定路径
WORKDIR /home/course
# 复制jar文件到路径
COPY ./jar/course-visual-monitor.jar /home/course/course-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","course-visual-monitor.jar"]